# /* Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: MIT-0 */
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.91.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
      # args:
      # - --args=--module
      # - --args=--disbale-rule=terraform_required_providers
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
        - --hook-config=--add-to-existing-file=true     # Boolean. true or false
        - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
        - --hook-config=--use-standard-markers=true     # Boolean. Defaults in v1.x to false. Set to true for compatibility with terraform-docs
    # - id: terraform_validate
    - id: terraform_checkov
      args:
        - --args=--download-external-modules=false
        - --args=--skip-check=CKV_TF_2,CKV_TF_1
        # - --args=--compact
        - --args=--quiet
    # - id: terraform_trivy
    #   args:
    #   - --args=--skip-dirs="**/.terraform"
    #   - --args=--skip-db-update
    #   - --args=--offline-scan
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.1.1
    hooks:
    -   id: black
        # language_version: python3.11
        args: ["--line-length=130"]
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    -   id: isort
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: ["--max-line-length=130"]

-   repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v1.32.3 # The version of cfn-lint to use
    hooks:
      - id: cfn-lint
        files: workload-accounts/.*\.(json|yml|yaml)$

-   id: cfn-nag
    name: stelligent CFN_NAG
    description:  Looks for patterns in CloudFormation templates that may indicate insecure infrastructure.
    entry: cfn_nag_scan --input-path
    language: ruby
    files: \.(json|ya?ml|template)$
